apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-server
  template:
    metadata:
      labels:
        io.kompose.service: config-server
    spec:
      containers:
        - image: crisdocker10/config-server:latest 
          name: config-server
          ports:
            - containerPort: 8081
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8081/actuator/health
            failureThreshold: 5
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5