apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: gateway-server
  name: gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: gateway-server
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8081
            - name: SERVER_NETTY_MAX_HEADER_SIZE
              value: "16KB"
          image: crisdocker10/gateway-server:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - wget
                - -q
                - --spider
                - http://localhost:8080/actuator/health
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          name: gateway-server
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always