apiVersion: apps/v1
kind: Deployment
metadata:
  name: m1
  labels:
    app: m1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m1
  template:
    metadata:
      labels:
        app: m1
    spec:
      containers:
      - name: m1
        image: crisdocker10/m1:latest
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8081
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka/
      restartPolicy: Always