apiVersion: apps/v1
kind: Deployment
metadata:
  name: m2
  labels:
    app: m2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m2
  template:
    metadata:
      labels:
        app: m2
    spec:
      containers:
      - name: m2
        image: crisdocker10/m2:latest
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8081
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://eureka-server:8761/eureka
        - name: PORT
          value: "8080"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: m2
spec:
  type: ClusterIP
  selector:
    app: m2
  ports:
    - port: 8080
      targetPort: 8080