apiVersion: apps/v1
kind: Deployment
metadata:
  name: m4
  labels:
    app: m4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m4
  template:
    metadata:
      labels:
        app: m4
    spec:
      containers:
      - name: m4
        image: crisdocker10/m4:latest
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8081
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka/
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: m4
spec:
  type: ClusterIP
  selector:
    app: m4
  ports:
    - port: 8080
      targetPort: 8080