apiVersion: apps/v1
kind: Deployment
metadata:
  name: m4
  labels:
    io.kompose.service: m4
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: m4
  template:
    metadata:
      labels:
        io.kompose.service: m4
    spec:
      containers:
      - name: m4
        image: crisdocker10/m4:latest
        env:
        - name: SERVER_PORT
          value: "0"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://eureka-server:8761/eureka
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8081
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        # Base de Datos ms4_db
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-db:3306/ms4_db?allowPublicKeyRetrieval=true&useSSL=false
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: password
      restartPolicy: Always