apiVersion: apps/v1
kind: Deployment
metadata:
  name: m5
  labels:
    app: m5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m5
  template:
    metadata:
      labels:
        app: m5
    spec:
      containers:
      - name: m5
        image: crisdocker10/m5:latest
        imagePullPolicy: Always
        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8081
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://eureka-server:8761/eureka
        - name: PORT
          value: "8080"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: m5
spec:
  type: ClusterIP
  selector:
    app: m5
  ports:
    - port: 8080
      targetPort: 8080