apiVersion: apps/v1
kind: Deployment
metadata:
  name: m6
  labels:
    app: m6  # Etiqueta est√°ndar (sin kompose)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m6
  template:
    metadata:
      labels:
        app: m6
    spec:
      containers:
        - name: m6
          image: crisdocker10/m6:latest
          imagePullPolicy: Always 
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eureka-server:8761/eureka
            - name: PORT
              value: "0"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8081
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      restartPolicy: Always