apiVersion: apps/v1
kind: Deployment
metadata:
  name: m7
  labels:
    app: m7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m7
  template:
    metadata:
      labels:
        app: m7
    spec:
      containers:
      - name: m7
        image: quay.io/keycloak/keycloak:25.0
        args: ["start-dev"]
        env:
        - name: KC_HOSTNAME_URL
          value: "http://172.17.244.157:30080"
        - name: KC_HOSTNAME_ADMIN_URL
          value: "http://172.17.244.157:30080"
        - name: KEYCLOAK_ADMIN
          value: "cristingeso"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "rodrigo12"
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://postgres-db:5432/m7_db"
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_PROXY_HEADERS
          value: "xforwarded" 
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: keycloak-service 
spec:
  type: ClusterIP         
  selector:
    app: m7
  ports:
    - name: http
      port: 9090          
      targetPort: 8080    
