apiVersion: apps/v1
kind: Deployment
metadata:
  name: m7
  labels:
    io.kompose.service: m7
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: m7
  template:
    metadata:
      labels:
        io.kompose.service: m7
    spec:
      containers:
      - name: m7
        image: quay.io/keycloak/keycloak:25.0
        args: ["start-dev"] # Modo desarrollo (Habilita HTTP y desactiva caché estricta)
        env:
        # --- CONFIGURACIÓN DE KEYCLOAK ---
        # Usuario Admin
        - name: KEYCLOAK_ADMIN
          value: "cristingeso"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "rodrigo12"
        
        # Conexión a Base de Datos
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://postgres-db:5432/m7_db"
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password

        # Configuración HTTP (Importante para que no pida HTTPS)
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    io.kompose.service: m7
  ports:
    - protocol: TCP
      port: 9090       
      targetPort: 8080 
  type: NodePort
