apiVersion: apps/v1
kind: Deployment
metadata:
  name: m7
  labels:
    io.kompose.service: m7
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: m7
  template:
    metadata:
      labels:
        io.kompose.service: m7
    spec:
      containers:
      - name: m7
        image: quay.io/keycloak/keycloak:25.0
        args: ["start-dev"]
        env:
        - name: SERVER_PORT
          value: "0"  # Puerto dinámico
        - name: PORT
          value: "0"  # Puerto dinámico
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://eureka-server:8761/eureka
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8081
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"

        # --- CONFIGURACIÓN REAL DE KEYCLOAK ---
        - name: KEYCLOAK_ADMIN
          value: "cristingeso"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "rodrigo12"
        
        # Conexión a Base de Datos (Postgres)
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://postgres-db:5432/m7_db"
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password

        # Configuración de Red
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
          
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    io.kompose.service: m7
  ports:
    - protocol: TCP
      port: 9090  # El puerto accesible desde fuera del clúster
      targetPort: 0  # Redirige al puerto dinámico del contenedor
  type: NodePort  # Exposición del servicio usando NodePort
