apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS dbtoolrent;
    CREATE DATABASE IF NOT EXISTS ms1_db;
    CREATE DATABASE IF NOT EXISTS ms2_db;
    CREATE DATABASE IF NOT EXISTS ms3_db;
    CREATE DATABASE IF NOT EXISTS ms4_db;
    CREATE DATABASE IF NOT EXISTS ms5_db;
    CREATE DATABASE IF NOT EXISTS ms6_db;
    
    -- Dar permisos al usuario ADMIN sobre todas las bases
    GRANT ALL PRIVILEGES ON *.* TO 'ADMIN'@'%';
    FLUSH PRIVILEGES;